import Foundation

nonisolated struct AirlineInfo: Sendable, Identifiable, Hashable {
    let iata: String
    let name: String
    let country: String

    var id: String { iata }

    var displayName: String { "\(name) (\(iata))" }
}

enum AirlineDatabase {
    static func search(_ query: String) -> [AirlineInfo] {
        if query.isEmpty { return [] }
        let q = query.lowercased()
        return allAirlines.filter {
            $0.iata.lowercased().contains(q) ||
            $0.name.lowercased().contains(q) ||
            $0.country.lowercased().contains(q)
        }
    }

    static let allAirlines: [AirlineInfo] = [
        // United States
        AirlineInfo(iata: "AA", name: "American Airlines", country: "United States"),
        AirlineInfo(iata: "DL", name: "Delta Air Lines", country: "United States"),
        AirlineInfo(iata: "UA", name: "United Airlines", country: "United States"),
        AirlineInfo(iata: "WN", name: "Southwest Airlines", country: "United States"),
        AirlineInfo(iata: "B6", name: "JetBlue Airways", country: "United States"),
        AirlineInfo(iata: "AS", name: "Alaska Airlines", country: "United States"),
        AirlineInfo(iata: "NK", name: "Spirit Airlines", country: "United States"),
        AirlineInfo(iata: "F9", name: "Frontier Airlines", country: "United States"),
        AirlineInfo(iata: "G4", name: "Allegiant Air", country: "United States"),
        AirlineInfo(iata: "HA", name: "Hawaiian Airlines", country: "United States"),
        AirlineInfo(iata: "SY", name: "Sun Country Airlines", country: "United States"),
        AirlineInfo(iata: "MX", name: "Breeze Airways", country: "United States"),
        AirlineInfo(iata: "XP", name: "Avelo Airlines", country: "United States"),
        // Canada
        AirlineInfo(iata: "AC", name: "Air Canada", country: "Canada"),
        AirlineInfo(iata: "WS", name: "WestJet", country: "Canada"),
        AirlineInfo(iata: "PD", name: "Porter Airlines", country: "Canada"),
        AirlineInfo(iata: "TS", name: "Air Transat", country: "Canada"),
        AirlineInfo(iata: "WG", name: "Sunwing Airlines", country: "Canada"),
        AirlineInfo(iata: "QK", name: "Jazz Aviation", country: "Canada"),
        // Europe - UK & Ireland
        AirlineInfo(iata: "BA", name: "British Airways", country: "United Kingdom"),
        AirlineInfo(iata: "VS", name: "Virgin Atlantic", country: "United Kingdom"),
        AirlineInfo(iata: "U2", name: "easyJet", country: "United Kingdom"),
        AirlineInfo(iata: "LS", name: "Jet2.com", country: "United Kingdom"),
        AirlineInfo(iata: "BY", name: "TUI Airways", country: "United Kingdom"),
        AirlineInfo(iata: "EI", name: "Aer Lingus", country: "Ireland"),
        AirlineInfo(iata: "FR", name: "Ryanair", country: "Ireland"),
        // Europe - Central & Western
        AirlineInfo(iata: "LH", name: "Lufthansa", country: "Germany"),
        AirlineInfo(iata: "EW", name: "Eurowings", country: "Germany"),
        AirlineInfo(iata: "DE", name: "Condor", country: "Germany"),
        AirlineInfo(iata: "4Y", name: "Discover Airlines", country: "Germany"),
        AirlineInfo(iata: "AF", name: "Air France", country: "France"),
        AirlineInfo(iata: "TO", name: "Transavia France", country: "France"),
        AirlineInfo(iata: "SS", name: "Corsair International", country: "France"),
        AirlineInfo(iata: "KL", name: "KLM Royal Dutch Airlines", country: "Netherlands"),
        AirlineInfo(iata: "HV", name: "Transavia", country: "Netherlands"),
        AirlineInfo(iata: "LX", name: "Swiss International Air Lines", country: "Switzerland"),
        AirlineInfo(iata: "OS", name: "Austrian Airlines", country: "Austria"),
        AirlineInfo(iata: "SN", name: "Brussels Airlines", country: "Belgium"),
        AirlineInfo(iata: "LO", name: "LOT Polish Airlines", country: "Poland"),
        AirlineInfo(iata: "OK", name: "Czech Airlines", country: "Czech Republic"),
        AirlineInfo(iata: "OU", name: "Croatia Airlines", country: "Croatia"),
        AirlineInfo(iata: "JP", name: "Adria Airways", country: "Slovenia"),
        AirlineInfo(iata: "JU", name: "Air Serbia", country: "Serbia"),
        AirlineInfo(iata: "RO", name: "TAROM", country: "Romania"),
        AirlineInfo(iata: "W6", name: "Wizz Air", country: "Hungary"),
        AirlineInfo(iata: "FB", name: "Bulgaria Air", country: "Bulgaria"),
        AirlineInfo(iata: "BT", name: "airBaltic", country: "Latvia"),
        // Europe - Iberian & Mediterranean
        AirlineInfo(iata: "IB", name: "Iberia", country: "Spain"),
        AirlineInfo(iata: "VY", name: "Vueling", country: "Spain"),
        AirlineInfo(iata: "UX", name: "Air Europa", country: "Spain"),
        AirlineInfo(iata: "I2", name: "Iberia Express", country: "Spain"),
        AirlineInfo(iata: "TP", name: "TAP Air Portugal", country: "Portugal"),
        AirlineInfo(iata: "AZ", name: "ITA Airways", country: "Italy"),
        AirlineInfo(iata: "NO", name: "Neos", country: "Italy"),
        AirlineInfo(iata: "A3", name: "Aegean Airlines", country: "Greece"),
        AirlineInfo(iata: "OA", name: "Olympic Air", country: "Greece"),
        AirlineInfo(iata: "KM", name: "Air Malta", country: "Malta"),
        AirlineInfo(iata: "CY", name: "Cyprus Airways", country: "Cyprus"),
        // Europe - Nordic
        AirlineInfo(iata: "SK", name: "SAS Scandinavian Airlines", country: "Sweden"),
        AirlineInfo(iata: "DY", name: "Norwegian Air Shuttle", country: "Norway"),
        AirlineInfo(iata: "AY", name: "Finnair", country: "Finland"),
        AirlineInfo(iata: "FI", name: "Icelandair", country: "Iceland"),
        AirlineInfo(iata: "WW", name: "WOW air", country: "Iceland"),
        AirlineInfo(iata: "RC", name: "Atlantic Airways", country: "Faroe Islands"),
        // Turkey
        AirlineInfo(iata: "TK", name: "Turkish Airlines", country: "Turkey"),
        AirlineInfo(iata: "PC", name: "Pegasus Airlines", country: "Turkey"),
        AirlineInfo(iata: "XQ", name: "SunExpress", country: "Turkey"),
        AirlineInfo(iata: "XC", name: "Corendon Airlines", country: "Turkey"),
        // Middle East
        AirlineInfo(iata: "EK", name: "Emirates", country: "United Arab Emirates"),
        AirlineInfo(iata: "EY", name: "Etihad Airways", country: "United Arab Emirates"),
        AirlineInfo(iata: "FZ", name: "flydubai", country: "United Arab Emirates"),
        AirlineInfo(iata: "G9", name: "Air Arabia", country: "United Arab Emirates"),
        AirlineInfo(iata: "QR", name: "Qatar Airways", country: "Qatar"),
        AirlineInfo(iata: "SV", name: "Saudia", country: "Saudi Arabia"),
        AirlineInfo(iata: "XY", name: "flynas", country: "Saudi Arabia"),
        AirlineInfo(iata: "F3", name: "Flyadeal", country: "Saudi Arabia"),
        AirlineInfo(iata: "WY", name: "Oman Air", country: "Oman"),
        AirlineInfo(iata: "GF", name: "Gulf Air", country: "Bahrain"),
        AirlineInfo(iata: "KU", name: "Kuwait Airways", country: "Kuwait"),
        AirlineInfo(iata: "RJ", name: "Royal Jordanian", country: "Jordan"),
        AirlineInfo(iata: "ME", name: "Middle East Airlines", country: "Lebanon"),
        AirlineInfo(iata: "LY", name: "El Al Israel Airlines", country: "Israel"),
        AirlineInfo(iata: "6E", name: "IndiGo", country: "India"),
        AirlineInfo(iata: "W5", name: "Mahan Air", country: "Iran"),
        AirlineInfo(iata: "IR", name: "Iran Air", country: "Iran"),
        AirlineInfo(iata: "IA", name: "Iraqi Airways", country: "Iraq"),
        // Asia - East
        AirlineInfo(iata: "CX", name: "Cathay Pacific", country: "Hong Kong"),
        AirlineInfo(iata: "HX", name: "Hong Kong Airlines", country: "Hong Kong"),
        AirlineInfo(iata: "CI", name: "China Airlines", country: "Taiwan"),
        AirlineInfo(iata: "BR", name: "EVA Air", country: "Taiwan"),
        AirlineInfo(iata: "IT", name: "Tigerair Taiwan", country: "Taiwan"),
        AirlineInfo(iata: "CA", name: "Air China", country: "China"),
        AirlineInfo(iata: "MU", name: "China Eastern Airlines", country: "China"),
        AirlineInfo(iata: "CZ", name: "China Southern Airlines", country: "China"),
        AirlineInfo(iata: "HU", name: "Hainan Airlines", country: "China"),
        AirlineInfo(iata: "3U", name: "Sichuan Airlines", country: "China"),
        AirlineInfo(iata: "MF", name: "Xiamen Airlines", country: "China"),
        AirlineInfo(iata: "ZH", name: "Shenzhen Airlines", country: "China"),
        AirlineInfo(iata: "FM", name: "Shanghai Airlines", country: "China"),
        AirlineInfo(iata: "SC", name: "Shandong Airlines", country: "China"),
        AirlineInfo(iata: "9C", name: "Spring Airlines", country: "China"),
        AirlineInfo(iata: "G5", name: "China Express Airlines", country: "China"),
        AirlineInfo(iata: "JL", name: "Japan Airlines", country: "Japan"),
        AirlineInfo(iata: "NH", name: "All Nippon Airways", country: "Japan"),
        AirlineInfo(iata: "MM", name: "Peach Aviation", country: "Japan"),
        AirlineInfo(iata: "BC", name: "Skymark Airlines", country: "Japan"),
        AirlineInfo(iata: "JW", name: "Vanilla Air", country: "Japan"),
        AirlineInfo(iata: "GK", name: "Jetstar Japan", country: "Japan"),
        AirlineInfo(iata: "HD", name: "AirDo", country: "Japan"),
        AirlineInfo(iata: "7C", name: "Jeju Air", country: "South Korea"),
        AirlineInfo(iata: "KE", name: "Korean Air", country: "South Korea"),
        AirlineInfo(iata: "OZ", name: "Asiana Airlines", country: "South Korea"),
        AirlineInfo(iata: "LJ", name: "Jin Air", country: "South Korea"),
        AirlineInfo(iata: "TW", name: "T'way Air", country: "South Korea"),
        AirlineInfo(iata: "BX", name: "Air Busan", country: "South Korea"),
        AirlineInfo(iata: "ZE", name: "Eastar Jet", country: "South Korea"),
        AirlineInfo(iata: "RS", name: "Air Seoul", country: "South Korea"),
        AirlineInfo(iata: "OM", name: "MIAT Mongolian Airlines", country: "Mongolia"),
        // Asia - Southeast
        AirlineInfo(iata: "SQ", name: "Singapore Airlines", country: "Singapore"),
        AirlineInfo(iata: "TR", name: "Scoot", country: "Singapore"),
        AirlineInfo(iata: "MH", name: "Malaysia Airlines", country: "Malaysia"),
        AirlineInfo(iata: "AK", name: "AirAsia", country: "Malaysia"),
        AirlineInfo(iata: "D7", name: "AirAsia X", country: "Malaysia"),
        AirlineInfo(iata: "OD", name: "Batik Air Malaysia", country: "Malaysia"),
        AirlineInfo(iata: "FY", name: "Firefly", country: "Malaysia"),
        AirlineInfo(iata: "GA", name: "Garuda Indonesia", country: "Indonesia"),
        AirlineInfo(iata: "QG", name: "Citilink", country: "Indonesia"),
        AirlineInfo(iata: "JT", name: "Lion Air", country: "Indonesia"),
        AirlineInfo(iata: "ID", name: "Batik Air", country: "Indonesia"),
        AirlineInfo(iata: "QZ", name: "Indonesia AirAsia", country: "Indonesia"),
        AirlineInfo(iata: "TG", name: "Thai Airways", country: "Thailand"),
        AirlineInfo(iata: "FD", name: "Thai AirAsia", country: "Thailand"),
        AirlineInfo(iata: "WE", name: "Thai Smile", country: "Thailand"),
        AirlineInfo(iata: "DD", name: "Nok Air", country: "Thailand"),
        AirlineInfo(iata: "SL", name: "Thai Lion Air", country: "Thailand"),
        AirlineInfo(iata: "VN", name: "Vietnam Airlines", country: "Vietnam"),
        AirlineInfo(iata: "VJ", name: "VietJet Air", country: "Vietnam"),
        AirlineInfo(iata: "BL", name: "Pacific Airlines", country: "Vietnam"),
        AirlineInfo(iata: "QV", name: "Lao Airlines", country: "Laos"),
        AirlineInfo(iata: "K6", name: "Cambodia Angkor Air", country: "Cambodia"),
        AirlineInfo(iata: "UB", name: "Myanmar National Airlines", country: "Myanmar"),
        AirlineInfo(iata: "PR", name: "Philippine Airlines", country: "Philippines"),
        AirlineInfo(iata: "5J", name: "Cebu Pacific", country: "Philippines"),
        AirlineInfo(iata: "Z2", name: "AirAsia Philippines", country: "Philippines"),
        AirlineInfo(iata: "NX", name: "Air Macau", country: "Macau"),
        AirlineInfo(iata: "BI", name: "Royal Brunei Airlines", country: "Brunei"),
        // Asia - South
        AirlineInfo(iata: "AI", name: "Air India", country: "India"),
        AirlineInfo(iata: "UK", name: "Vistara", country: "India"),
        AirlineInfo(iata: "SG", name: "SpiceJet", country: "India"),
        AirlineInfo(iata: "IX", name: "Air India Express", country: "India"),
        AirlineInfo(iata: "G8", name: "Go First", country: "India"),
        AirlineInfo(iata: "I5", name: "AirAsia India", country: "India"),
        AirlineInfo(iata: "PK", name: "Pakistan International Airlines", country: "Pakistan"),
        AirlineInfo(iata: "BG", name: "Biman Bangladesh Airlines", country: "Bangladesh"),
        AirlineInfo(iata: "UL", name: "SriLankan Airlines", country: "Sri Lanka"),
        AirlineInfo(iata: "Q2", name: "Maldivian", country: "Maldives"),
        AirlineInfo(iata: "RA", name: "Nepal Airlines", country: "Nepal"),
        AirlineInfo(iata: "KB", name: "Drukair", country: "Bhutan"),
        // Oceania
        AirlineInfo(iata: "QF", name: "Qantas", country: "Australia"),
        AirlineInfo(iata: "VA", name: "Virgin Australia", country: "Australia"),
        AirlineInfo(iata: "JQ", name: "Jetstar Airways", country: "Australia"),
        AirlineInfo(iata: "TT", name: "Tigerair Australia", country: "Australia"),
        AirlineInfo(iata: "RE", name: "Rex Airlines", country: "Australia"),
        AirlineInfo(iata: "BK", name: "Bonza", country: "Australia"),
        AirlineInfo(iata: "NZ", name: "Air New Zealand", country: "New Zealand"),
        AirlineInfo(iata: "FJ", name: "Fiji Airways", country: "Fiji"),
        AirlineInfo(iata: "TN", name: "Air Tahiti Nui", country: "French Polynesia"),
        AirlineInfo(iata: "SB", name: "Aircalin", country: "New Caledonia"),
        // Africa
        AirlineInfo(iata: "ET", name: "Ethiopian Airlines", country: "Ethiopia"),
        AirlineInfo(iata: "SA", name: "South African Airways", country: "South Africa"),
        AirlineInfo(iata: "FA", name: "FlySafair", country: "South Africa"),
        AirlineInfo(iata: "KQ", name: "Kenya Airways", country: "Kenya"),
        AirlineInfo(iata: "MS", name: "EgyptAir", country: "Egypt"),
        AirlineInfo(iata: "AT", name: "Royal Air Maroc", country: "Morocco"),
        AirlineInfo(iata: "TU", name: "Tunisair", country: "Tunisia"),
        AirlineInfo(iata: "AH", name: "Air Algérie", country: "Algeria"),
        AirlineInfo(iata: "WB", name: "RwandAir", country: "Rwanda"),
        AirlineInfo(iata: "TC", name: "Air Tanzania", country: "Tanzania"),
        AirlineInfo(iata: "UM", name: "Air Zimbabwe", country: "Zimbabwe"),
        AirlineInfo(iata: "SW", name: "Air Namibia", country: "Namibia"),
        AirlineInfo(iata: "MK", name: "Air Mauritius", country: "Mauritius"),
        AirlineInfo(iata: "HM", name: "Air Seychelles", country: "Seychelles"),
        AirlineInfo(iata: "MD", name: "Air Madagascar", country: "Madagascar"),
        AirlineInfo(iata: "W3", name: "Arik Air", country: "Nigeria"),
        AirlineInfo(iata: "P4", name: "Air Peace", country: "Nigeria"),
        AirlineInfo(iata: "HF", name: "Air Côte d'Ivoire", country: "Côte d'Ivoire"),
        AirlineInfo(iata: "HC", name: "Air Senegal", country: "Senegal"),
        // Latin America
        AirlineInfo(iata: "LA", name: "LATAM Airlines", country: "Chile"),
        AirlineInfo(iata: "JJ", name: "LATAM Airlines Brasil", country: "Brazil"),
        AirlineInfo(iata: "LP", name: "LATAM Airlines Peru", country: "Peru"),
        AirlineInfo(iata: "4C", name: "LATAM Airlines Colombia", country: "Colombia"),
        AirlineInfo(iata: "XL", name: "LATAM Airlines Ecuador", country: "Ecuador"),
        AirlineInfo(iata: "AD", name: "Azul Brazilian Airlines", country: "Brazil"),
        AirlineInfo(iata: "G3", name: "GOL Linhas Aéreas", country: "Brazil"),
        AirlineInfo(iata: "AR", name: "Aerolíneas Argentinas", country: "Argentina"),
        AirlineInfo(iata: "FO", name: "Flybondi", country: "Argentina"),
        AirlineInfo(iata: "H2", name: "Sky Airline", country: "Chile"),
        AirlineInfo(iata: "JA", name: "JetSMART", country: "Chile"),
        AirlineInfo(iata: "AV", name: "Avianca", country: "Colombia"),
        AirlineInfo(iata: "CM", name: "Copa Airlines", country: "Panama"),
        AirlineInfo(iata: "AM", name: "Aeroméxico", country: "Mexico"),
        AirlineInfo(iata: "4O", name: "Interjet", country: "Mexico"),
        AirlineInfo(iata: "Y4", name: "Volaris", country: "Mexico"),
        AirlineInfo(iata: "VB", name: "VivaAerobus", country: "Mexico"),
        AirlineInfo(iata: "LR", name: "LACSA (Avianca Costa Rica)", country: "Costa Rica"),
        AirlineInfo(iata: "TA", name: "TACA International", country: "El Salvador"),
        AirlineInfo(iata: "BW", name: "Caribbean Airlines", country: "Trinidad and Tobago"),
        AirlineInfo(iata: "UP", name: "Bahamasair", country: "Bahamas"),
        AirlineInfo(iata: "CU", name: "Cubana de Aviación", country: "Cuba"),
        AirlineInfo(iata: "DO", name: "Sky High Aviation", country: "Dominican Republic"),
        // Central Asia & Russia
        AirlineInfo(iata: "SU", name: "Aeroflot", country: "Russia"),
        AirlineInfo(iata: "S7", name: "S7 Airlines", country: "Russia"),
        AirlineInfo(iata: "DP", name: "Pobeda", country: "Russia"),
        AirlineInfo(iata: "UT", name: "UTair", country: "Russia"),
        AirlineInfo(iata: "U6", name: "Ural Airlines", country: "Russia"),
        AirlineInfo(iata: "KC", name: "Air Astana", country: "Kazakhstan"),
        AirlineInfo(iata: "QH", name: "Bamboo Airways", country: "Vietnam"),
        AirlineInfo(iata: "HY", name: "Uzbekistan Airways", country: "Uzbekistan"),
        AirlineInfo(iata: "J2", name: "Azerbaijan Airlines", country: "Azerbaijan"),
        AirlineInfo(iata: "A9", name: "Georgian Airways", country: "Georgia"),
        // Additional European
        AirlineInfo(iata: "BE", name: "Flybe", country: "United Kingdom"),
        AirlineInfo(iata: "ZB", name: "Monarch Airlines", country: "United Kingdom"),
        AirlineInfo(iata: "MT", name: "Thomas Cook Airlines", country: "United Kingdom"),
        AirlineInfo(iata: "EN", name: "Air Dolomiti", country: "Italy"),
        AirlineInfo(iata: "IG", name: "Air Italy", country: "Italy"),
        AirlineInfo(iata: "V7", name: "Volotea", country: "Spain"),
        AirlineInfo(iata: "OR", name: "TUI fly Netherlands", country: "Netherlands"),
        AirlineInfo(iata: "PS", name: "Ukraine International Airlines", country: "Ukraine"),
        AirlineInfo(iata: "QS", name: "Smartwings", country: "Czech Republic"),
        AirlineInfo(iata: "YM", name: "Montenegro Airlines", country: "Montenegro"),
        AirlineInfo(iata: "0B", name: "Blue Air", country: "Romania"),
        AirlineInfo(iata: "T7", name: "Twin Jet", country: "France"),
        AirlineInfo(iata: "5O", name: "ASL Airlines France", country: "France"),
        AirlineInfo(iata: "AP", name: "AlbaStar", country: "Spain"),
        AirlineInfo(iata: "EB", name: "Wamos Air", country: "Spain"),
        AirlineInfo(iata: "NT", name: "Binter Canarias", country: "Spain"),
        AirlineInfo(iata: "YW", name: "Air Nostrum", country: "Spain"),
        AirlineInfo(iata: "X3", name: "TUI fly Deutschland", country: "Germany"),
        AirlineInfo(iata: "AB", name: "Air Berlin", country: "Germany"),
        AirlineInfo(iata: "8Q", name: "Onur Air", country: "Turkey"),
        AirlineInfo(iata: "YK", name: "Avia Traffic Company", country: "Kyrgyzstan"),
        AirlineInfo(iata: "T5", name: "Turkmenistan Airlines", country: "Turkmenistan"),
        AirlineInfo(iata: "B2", name: "Belavia", country: "Belarus"),
        AirlineInfo(iata: "TF", name: "Braathens Regional", country: "Sweden"),
        AirlineInfo(iata: "WF", name: "Widerøe", country: "Norway"),
        AirlineInfo(iata: "GL", name: "Air Greenland", country: "Greenland"),
        // Additional Americas
        AirlineInfo(iata: "NK", name: "Spirit Airlines", country: "United States"),
        AirlineInfo(iata: "OH", name: "PSA Airlines", country: "United States"),
        AirlineInfo(iata: "OO", name: "SkyWest Airlines", country: "United States"),
        AirlineInfo(iata: "YX", name: "Republic Airways", country: "United States"),
        AirlineInfo(iata: "9K", name: "Cape Air", country: "United States"),
        AirlineInfo(iata: "KS", name: "Peninsula Airways", country: "United States"),
        AirlineInfo(iata: "ZW", name: "Air Wisconsin", country: "United States"),
        AirlineInfo(iata: "C5", name: "CommutAir", country: "United States"),
        AirlineInfo(iata: "PT", name: "Piedmont Airlines", country: "United States"),
        AirlineInfo(iata: "9X", name: "Southern Airways Express", country: "United States"),
        AirlineInfo(iata: "2P", name: "PAL Express", country: "Philippines"),
        AirlineInfo(iata: "P5", name: "Wingo", country: "Colombia"),
        AirlineInfo(iata: "5Z", name: "Voepass Linhas Aéreas", country: "Brazil"),
        AirlineInfo(iata: "2Z", name: "Passaredo", country: "Brazil"),
        AirlineInfo(iata: "OB", name: "Boliviana de Aviación", country: "Bolivia"),
        AirlineInfo(iata: "PZ", name: "LATAM Airlines Paraguay", country: "Paraguay"),
        AirlineInfo(iata: "VE", name: "EaseFly", country: "Venezuela"),
        AirlineInfo(iata: "GY", name: "Colorful Guizhou Airlines", country: "China"),
        // Additional Asia
        AirlineInfo(iata: "3K", name: "Jetstar Asia", country: "Singapore"),
        AirlineInfo(iata: "MI", name: "SilkAir", country: "Singapore"),
        AirlineInfo(iata: "UO", name: "HK Express", country: "Hong Kong"),
        AirlineInfo(iata: "KA", name: "Cathay Dragon", country: "Hong Kong"),
        AirlineInfo(iata: "9W", name: "Jet Airways", country: "India"),
        AirlineInfo(iata: "RA", name: "Nepal Airlines", country: "Nepal"),
        AirlineInfo(iata: "S2", name: "JetLite", country: "India"),
        AirlineInfo(iata: "8M", name: "Myanmar Airways International", country: "Myanmar"),
        AirlineInfo(iata: "PG", name: "Bangkok Airways", country: "Thailand"),
        AirlineInfo(iata: "RQ", name: "Kam Air", country: "Afghanistan"),
        // Additional Middle East & Africa
        AirlineInfo(iata: "J9", name: "Jazeera Airways", country: "Kuwait"),
        AirlineInfo(iata: "R5", name: "Jordan Aviation", country: "Jordan"),
        AirlineInfo(iata: "NP", name: "Nile Air", country: "Egypt"),
        AirlineInfo(iata: "8U", name: "Afriqiyah Airways", country: "Libya"),
        AirlineInfo(iata: "LN", name: "Libyan Airlines", country: "Libya"),
        AirlineInfo(iata: "ZL", name: "Regional Express", country: "Australia"),
        AirlineInfo(iata: "PX", name: "Air Niugini", country: "Papua New Guinea"),
        AirlineInfo(iata: "IE", name: "Solomon Airlines", country: "Solomon Islands"),
        AirlineInfo(iata: "NF", name: "Air Vanuatu", country: "Vanuatu"),
        AirlineInfo(iata: "ON", name: "Nauru Airlines", country: "Nauru"),
    ]
}
