import Foundation

nonisolated struct AirportInfo: Sendable, Identifiable, Hashable {
    let iata: String
    let name: String
    let city: String
    let country: String

    var id: String { iata }

    var displayName: String { "\(iata) — \(name)" }
    var subtitle: String { "\(city), \(country)" }
}

enum AirportDatabase {
    static func search(_ query: String) -> [AirportInfo] {
        if query.isEmpty { return [] }
        let q = query.lowercased()
        return allAirports.filter {
            $0.iata.lowercased().contains(q) ||
            $0.name.lowercased().contains(q) ||
            $0.city.lowercased().contains(q) ||
            $0.country.lowercased().contains(q)
        }
    }

    static let allAirports: [AirportInfo] = [
        AirportInfo(iata: "ATL", name: "Hartsfield-Jackson Atlanta Intl", city: "Atlanta", country: "United States"),
        AirportInfo(iata: "PEK", name: "Beijing Capital Intl", city: "Beijing", country: "China"),
        AirportInfo(iata: "PKX", name: "Beijing Daxing Intl", city: "Beijing", country: "China"),
        AirportInfo(iata: "DXB", name: "Dubai Intl", city: "Dubai", country: "United Arab Emirates"),
        AirportInfo(iata: "DFW", name: "Dallas/Fort Worth Intl", city: "Dallas", country: "United States"),
        AirportInfo(iata: "DEN", name: "Denver Intl", city: "Denver", country: "United States"),
        AirportInfo(iata: "ORD", name: "O'Hare Intl", city: "Chicago", country: "United States"),
        AirportInfo(iata: "LHR", name: "Heathrow", city: "London", country: "United Kingdom"),
        AirportInfo(iata: "LAX", name: "Los Angeles Intl", city: "Los Angeles", country: "United States"),
        AirportInfo(iata: "IST", name: "Istanbul", city: "Istanbul", country: "Turkey"),
        AirportInfo(iata: "CDG", name: "Charles de Gaulle", city: "Paris", country: "France"),
        AirportInfo(iata: "CAN", name: "Guangzhou Baiyun Intl", city: "Guangzhou", country: "China"),
        AirportInfo(iata: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", country: "Netherlands"),
        AirportInfo(iata: "DEL", name: "Indira Gandhi Intl", city: "New Delhi", country: "India"),
        AirportInfo(iata: "FRA", name: "Frankfurt", city: "Frankfurt", country: "Germany"),
        AirportInfo(iata: "HND", name: "Haneda", city: "Tokyo", country: "Japan"),
        AirportInfo(iata: "NRT", name: "Narita Intl", city: "Tokyo", country: "Japan"),
        AirportInfo(iata: "JFK", name: "John F. Kennedy Intl", city: "New York", country: "United States"),
        AirportInfo(iata: "SIN", name: "Changi", city: "Singapore", country: "Singapore"),
        AirportInfo(iata: "ICN", name: "Incheon Intl", city: "Seoul", country: "South Korea"),
        AirportInfo(iata: "BKK", name: "Suvarnabhumi", city: "Bangkok", country: "Thailand"),
        AirportInfo(iata: "SFO", name: "San Francisco Intl", city: "San Francisco", country: "United States"),
        AirportInfo(iata: "SEA", name: "Seattle-Tacoma Intl", city: "Seattle", country: "United States"),
        AirportInfo(iata: "MCO", name: "Orlando Intl", city: "Orlando", country: "United States"),
        AirportInfo(iata: "EWR", name: "Newark Liberty Intl", city: "Newark", country: "United States"),
        AirportInfo(iata: "MIA", name: "Miami Intl", city: "Miami", country: "United States"),
        AirportInfo(iata: "CLT", name: "Charlotte Douglas Intl", city: "Charlotte", country: "United States"),
        AirportInfo(iata: "LAS", name: "Harry Reid Intl", city: "Las Vegas", country: "United States"),
        AirportInfo(iata: "PHX", name: "Phoenix Sky Harbor Intl", city: "Phoenix", country: "United States"),
        AirportInfo(iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "United States"),
        AirportInfo(iata: "MSP", name: "Minneapolis-St Paul Intl", city: "Minneapolis", country: "United States"),
        AirportInfo(iata: "BOS", name: "Logan Intl", city: "Boston", country: "United States"),
        AirportInfo(iata: "DTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", country: "United States"),
        AirportInfo(iata: "PHL", name: "Philadelphia Intl", city: "Philadelphia", country: "United States"),
        AirportInfo(iata: "LGA", name: "LaGuardia", city: "New York", country: "United States"),
        AirportInfo(iata: "BWI", name: "Baltimore/Washington Intl", city: "Baltimore", country: "United States"),
        AirportInfo(iata: "SLC", name: "Salt Lake City Intl", city: "Salt Lake City", country: "United States"),
        AirportInfo(iata: "DCA", name: "Ronald Reagan Washington National", city: "Washington", country: "United States"),
        AirportInfo(iata: "IAD", name: "Washington Dulles Intl", city: "Washington", country: "United States"),
        AirportInfo(iata: "SAN", name: "San Diego Intl", city: "San Diego", country: "United States"),
        AirportInfo(iata: "TPA", name: "Tampa Intl", city: "Tampa", country: "United States"),
        AirportInfo(iata: "PDX", name: "Portland Intl", city: "Portland", country: "United States"),
        AirportInfo(iata: "HNL", name: "Daniel K. Inouye Intl", city: "Honolulu", country: "United States"),
        AirportInfo(iata: "STL", name: "St. Louis Lambert Intl", city: "St. Louis", country: "United States"),
        AirportInfo(iata: "BNA", name: "Nashville Intl", city: "Nashville", country: "United States"),
        AirportInfo(iata: "AUS", name: "Austin-Bergstrom Intl", city: "Austin", country: "United States"),
        AirportInfo(iata: "OAK", name: "Oakland Intl", city: "Oakland", country: "United States"),
        AirportInfo(iata: "SJC", name: "San Jose Intl", city: "San Jose", country: "United States"),
        AirportInfo(iata: "RDU", name: "Raleigh-Durham Intl", city: "Raleigh", country: "United States"),
        AirportInfo(iata: "MCI", name: "Kansas City Intl", city: "Kansas City", country: "United States"),
        AirportInfo(iata: "SMF", name: "Sacramento Intl", city: "Sacramento", country: "United States"),
        AirportInfo(iata: "CLE", name: "Cleveland Hopkins Intl", city: "Cleveland", country: "United States"),
        AirportInfo(iata: "IND", name: "Indianapolis Intl", city: "Indianapolis", country: "United States"),
        AirportInfo(iata: "PIT", name: "Pittsburgh Intl", city: "Pittsburgh", country: "United States"),
        AirportInfo(iata: "CMH", name: "John Glenn Columbus Intl", city: "Columbus", country: "United States"),
        AirportInfo(iata: "SAT", name: "San Antonio Intl", city: "San Antonio", country: "United States"),
        AirportInfo(iata: "RSW", name: "Southwest Florida Intl", city: "Fort Myers", country: "United States"),
        AirportInfo(iata: "MKE", name: "General Mitchell Intl", city: "Milwaukee", country: "United States"),
        AirportInfo(iata: "JAX", name: "Jacksonville Intl", city: "Jacksonville", country: "United States"),
        AirportInfo(iata: "OMA", name: "Eppley Airfield", city: "Omaha", country: "United States"),
        AirportInfo(iata: "RNO", name: "Reno-Tahoe Intl", city: "Reno", country: "United States"),
        AirportInfo(iata: "BUF", name: "Buffalo Niagara Intl", city: "Buffalo", country: "United States"),
        AirportInfo(iata: "ABQ", name: "Albuquerque Intl Sunport", city: "Albuquerque", country: "United States"),
        AirportInfo(iata: "OKC", name: "Will Rogers World", city: "Oklahoma City", country: "United States"),
        AirportInfo(iata: "TUL", name: "Tulsa Intl", city: "Tulsa", country: "United States"),
        AirportInfo(iata: "BDL", name: "Bradley Intl", city: "Hartford", country: "United States"),
        AirportInfo(iata: "ANC", name: "Ted Stevens Anchorage Intl", city: "Anchorage", country: "United States"),
        AirportInfo(iata: "PBI", name: "Palm Beach Intl", city: "West Palm Beach", country: "United States"),
        AirportInfo(iata: "FLL", name: "Fort Lauderdale-Hollywood Intl", city: "Fort Lauderdale", country: "United States"),
        AirportInfo(iata: "SNA", name: "John Wayne", city: "Orange County", country: "United States"),
        AirportInfo(iata: "BUR", name: "Hollywood Burbank", city: "Burbank", country: "United States"),
        AirportInfo(iata: "DAL", name: "Dallas Love Field", city: "Dallas", country: "United States"),
        AirportInfo(iata: "HOU", name: "William P. Hobby", city: "Houston", country: "United States"),
        AirportInfo(iata: "MDW", name: "Midway Intl", city: "Chicago", country: "United States"),
        AirportInfo(iata: "MSY", name: "Louis Armstrong New Orleans Intl", city: "New Orleans", country: "United States"),
        AirportInfo(iata: "MEM", name: "Memphis Intl", city: "Memphis", country: "United States"),
        AirportInfo(iata: "CVG", name: "Cincinnati/Northern Kentucky Intl", city: "Cincinnati", country: "United States"),
        AirportInfo(iata: "SDF", name: "Louisville Muhammad Ali Intl", city: "Louisville", country: "United States"),
        AirportInfo(iata: "RIC", name: "Richmond Intl", city: "Richmond", country: "United States"),
        AirportInfo(iata: "ORF", name: "Norfolk Intl", city: "Norfolk", country: "United States"),
        AirportInfo(iata: "BOI", name: "Boise Airport", city: "Boise", country: "United States"),
        AirportInfo(iata: "OGG", name: "Kahului", city: "Maui", country: "United States"),
        AirportInfo(iata: "LIH", name: "Lihue", city: "Kauai", country: "United States"),
        AirportInfo(iata: "KOA", name: "Ellison Onizuka Kona Intl", city: "Kona", country: "United States"),
        AirportInfo(iata: "GEG", name: "Spokane Intl", city: "Spokane", country: "United States"),
        AirportInfo(iata: "TUS", name: "Tucson Intl", city: "Tucson", country: "United States"),
        AirportInfo(iata: "ELP", name: "El Paso Intl", city: "El Paso", country: "United States"),
        AirportInfo(iata: "LIT", name: "Bill and Hillary Clinton National", city: "Little Rock", country: "United States"),
        AirportInfo(iata: "DSM", name: "Des Moines Intl", city: "Des Moines", country: "United States"),
        AirportInfo(iata: "SYR", name: "Syracuse Hancock Intl", city: "Syracuse", country: "United States"),
        AirportInfo(iata: "ALB", name: "Albany Intl", city: "Albany", country: "United States"),
        AirportInfo(iata: "ROC", name: "Greater Rochester Intl", city: "Rochester", country: "United States"),
        AirportInfo(iata: "GSP", name: "Greenville-Spartanburg Intl", city: "Greenville", country: "United States"),
        AirportInfo(iata: "CHS", name: "Charleston Intl", city: "Charleston", country: "United States"),
        AirportInfo(iata: "SAV", name: "Savannah/Hilton Head Intl", city: "Savannah", country: "United States"),
        AirportInfo(iata: "PWM", name: "Portland Intl Jetport", city: "Portland", country: "United States"),
        AirportInfo(iata: "MYR", name: "Myrtle Beach Intl", city: "Myrtle Beach", country: "United States"),
        AirportInfo(iata: "BHM", name: "Birmingham-Shuttlesworth Intl", city: "Birmingham", country: "United States"),
        AirportInfo(iata: "HSV", name: "Huntsville Intl", city: "Huntsville", country: "United States"),
        AirportInfo(iata: "PNS", name: "Pensacola Intl", city: "Pensacola", country: "United States"),
        AirportInfo(iata: "VPS", name: "Destin-Fort Walton Beach", city: "Destin", country: "United States"),
        AirportInfo(iata: "GSO", name: "Piedmont Triad Intl", city: "Greensboro", country: "United States"),
        AirportInfo(iata: "DAY", name: "James M. Cox Dayton Intl", city: "Dayton", country: "United States"),
        AirportInfo(iata: "GRR", name: "Gerald R. Ford Intl", city: "Grand Rapids", country: "United States"),
        AirportInfo(iata: "XNA", name: "Northwest Arkansas National", city: "Fayetteville", country: "United States"),
        AirportInfo(iata: "ICT", name: "Wichita Dwight D. Eisenhower National", city: "Wichita", country: "United States"),
        AirportInfo(iata: "LGB", name: "Long Beach", city: "Long Beach", country: "United States"),
        AirportInfo(iata: "ONT", name: "Ontario Intl", city: "Ontario", country: "United States"),
        AirportInfo(iata: "PSP", name: "Palm Springs Intl", city: "Palm Springs", country: "United States"),
        AirportInfo(iata: "FAT", name: "Fresno Yosemite Intl", city: "Fresno", country: "United States"),
        AirportInfo(iata: "SBP", name: "San Luis Obispo County Regional", city: "San Luis Obispo", country: "United States"),
        AirportInfo(iata: "SBA", name: "Santa Barbara", city: "Santa Barbara", country: "United States"),
        AirportInfo(iata: "MFR", name: "Rogue Valley Intl", city: "Medford", country: "United States"),
        AirportInfo(iata: "EUG", name: "Eugene", city: "Eugene", country: "United States"),
        AirportInfo(iata: "BZN", name: "Bozeman Yellowstone Intl", city: "Bozeman", country: "United States"),
        AirportInfo(iata: "MSO", name: "Missoula Montana", city: "Missoula", country: "United States"),
        AirportInfo(iata: "BIL", name: "Billings Logan Intl", city: "Billings", country: "United States"),
        AirportInfo(iata: "FCA", name: "Glacier Park Intl", city: "Kalispell", country: "United States"),
        AirportInfo(iata: "JAC", name: "Jackson Hole", city: "Jackson Hole", country: "United States"),
        AirportInfo(iata: "SUN", name: "Friedman Memorial", city: "Sun Valley", country: "United States"),
        AirportInfo(iata: "ASE", name: "Aspen/Pitkin County", city: "Aspen", country: "United States"),
        AirportInfo(iata: "EGE", name: "Eagle County Regional", city: "Vail", country: "United States"),
        AirportInfo(iata: "HDN", name: "Yampa Valley", city: "Steamboat Springs", country: "United States"),
        AirportInfo(iata: "MTJ", name: "Montrose Regional", city: "Montrose", country: "United States"),
        AirportInfo(iata: "COS", name: "Colorado Springs", city: "Colorado Springs", country: "United States"),
        AirportInfo(iata: "GJT", name: "Grand Junction Regional", city: "Grand Junction", country: "United States"),
        AirportInfo(iata: "DRO", name: "Durango-La Plata County", city: "Durango", country: "United States"),
        AirportInfo(iata: "SGF", name: "Springfield-Branson National", city: "Springfield", country: "United States"),
        AirportInfo(iata: "FAR", name: "Hector Intl", city: "Fargo", country: "United States"),
        AirportInfo(iata: "BIS", name: "Bismarck", city: "Bismarck", country: "United States"),
        AirportInfo(iata: "RAP", name: "Rapid City Regional", city: "Rapid City", country: "United States"),
        AirportInfo(iata: "FSD", name: "Sioux Falls Regional", city: "Sioux Falls", country: "United States"),
        AirportInfo(iata: "PVD", name: "T.F. Green Intl", city: "Providence", country: "United States"),
        AirportInfo(iata: "MHT", name: "Manchester-Boston Regional", city: "Manchester", country: "United States"),
        AirportInfo(iata: "ORH", name: "Worcester Regional", city: "Worcester", country: "United States"),
        AirportInfo(iata: "ACK", name: "Nantucket Memorial", city: "Nantucket", country: "United States"),
        AirportInfo(iata: "MVY", name: "Martha's Vineyard", city: "Martha's Vineyard", country: "United States"),
        AirportInfo(iata: "HYA", name: "Cape Cod Gateway", city: "Hyannis", country: "United States"),
        AirportInfo(iata: "BTV", name: "Burlington Intl", city: "Burlington", country: "United States"),
        AirportInfo(iata: "SWF", name: "New York Stewart Intl", city: "Newburgh", country: "United States"),
        AirportInfo(iata: "ISP", name: "Long Island MacArthur", city: "Islip", country: "United States"),
        AirportInfo(iata: "HPN", name: "Westchester County", city: "White Plains", country: "United States"),
        AirportInfo(iata: "AVL", name: "Asheville Regional", city: "Asheville", country: "United States"),
        AirportInfo(iata: "CAK", name: "Akron-Canton", city: "Akron", country: "United States"),
        AirportInfo(iata: "LEX", name: "Blue Grass", city: "Lexington", country: "United States"),
        AirportInfo(iata: "SRQ", name: "Sarasota-Bradenton Intl", city: "Sarasota", country: "United States"),
        AirportInfo(iata: "PIE", name: "St. Pete-Clearwater Intl", city: "St. Petersburg", country: "United States"),
        AirportInfo(iata: "EYW", name: "Key West Intl", city: "Key West", country: "United States"),
        AirportInfo(iata: "DAB", name: "Daytona Beach Intl", city: "Daytona Beach", country: "United States"),
        AirportInfo(iata: "MLB", name: "Orlando Melbourne Intl", city: "Melbourne", country: "United States"),
        AirportInfo(iata: "GNV", name: "Gainesville Regional", city: "Gainesville", country: "United States"),
        AirportInfo(iata: "TLH", name: "Tallahassee Intl", city: "Tallahassee", country: "United States"),
        AirportInfo(iata: "MOB", name: "Mobile Regional", city: "Mobile", country: "United States"),
        AirportInfo(iata: "GPT", name: "Gulfport-Biloxi Intl", city: "Gulfport", country: "United States"),
        AirportInfo(iata: "SHV", name: "Shreveport Regional", city: "Shreveport", country: "United States"),
        AirportInfo(iata: "BTR", name: "Baton Rouge Metropolitan", city: "Baton Rouge", country: "United States"),
        AirportInfo(iata: "LFT", name: "Lafayette Regional", city: "Lafayette", country: "United States"),
        // Canada
        AirportInfo(iata: "YYZ", name: "Toronto Pearson Intl", city: "Toronto", country: "Canada"),
        AirportInfo(iata: "YVR", name: "Vancouver Intl", city: "Vancouver", country: "Canada"),
        AirportInfo(iata: "YUL", name: "Montréal-Pierre Elliott Trudeau Intl", city: "Montréal", country: "Canada"),
        AirportInfo(iata: "YYC", name: "Calgary Intl", city: "Calgary", country: "Canada"),
        AirportInfo(iata: "YEG", name: "Edmonton Intl", city: "Edmonton", country: "Canada"),
        AirportInfo(iata: "YOW", name: "Ottawa Macdonald-Cartier Intl", city: "Ottawa", country: "Canada"),
        AirportInfo(iata: "YWG", name: "Winnipeg James Armstrong Richardson Intl", city: "Winnipeg", country: "Canada"),
        AirportInfo(iata: "YHZ", name: "Halifax Stanfield Intl", city: "Halifax", country: "Canada"),
        AirportInfo(iata: "YQB", name: "Québec City Jean Lesage Intl", city: "Québec City", country: "Canada"),
        AirportInfo(iata: "YXE", name: "Saskatoon John G. Diefenbaker Intl", city: "Saskatoon", country: "Canada"),
        AirportInfo(iata: "YQR", name: "Regina Intl", city: "Regina", country: "Canada"),
        AirportInfo(iata: "YLW", name: "Kelowna Intl", city: "Kelowna", country: "Canada"),
        AirportInfo(iata: "YYJ", name: "Victoria Intl", city: "Victoria", country: "Canada"),
        AirportInfo(iata: "YXU", name: "London Intl", city: "London", country: "Canada"),
        AirportInfo(iata: "YKF", name: "Region of Waterloo Intl", city: "Kitchener", country: "Canada"),
        AirportInfo(iata: "YTZ", name: "Billy Bishop Toronto City", city: "Toronto", country: "Canada"),
        AirportInfo(iata: "YSJ", name: "Saint John", city: "Saint John", country: "Canada"),
        AirportInfo(iata: "YQM", name: "Greater Moncton Roméo LeBlanc Intl", city: "Moncton", country: "Canada"),
        AirportInfo(iata: "YFC", name: "Fredericton Intl", city: "Fredericton", country: "Canada"),
        AirportInfo(iata: "YYT", name: "St. John's Intl", city: "St. John's", country: "Canada"),
        // Europe
        AirportInfo(iata: "LGW", name: "Gatwick", city: "London", country: "United Kingdom"),
        AirportInfo(iata: "STN", name: "Stansted", city: "London", country: "United Kingdom"),
        AirportInfo(iata: "LTN", name: "Luton", city: "London", country: "United Kingdom"),
        AirportInfo(iata: "MAN", name: "Manchester", city: "Manchester", country: "United Kingdom"),
        AirportInfo(iata: "EDI", name: "Edinburgh", city: "Edinburgh", country: "United Kingdom"),
        AirportInfo(iata: "BHX", name: "Birmingham", city: "Birmingham", country: "United Kingdom"),
        AirportInfo(iata: "GLA", name: "Glasgow", city: "Glasgow", country: "United Kingdom"),
        AirportInfo(iata: "BRS", name: "Bristol", city: "Bristol", country: "United Kingdom"),
        AirportInfo(iata: "LCY", name: "London City", city: "London", country: "United Kingdom"),
        AirportInfo(iata: "NCL", name: "Newcastle", city: "Newcastle", country: "United Kingdom"),
        AirportInfo(iata: "BFS", name: "Belfast Intl", city: "Belfast", country: "United Kingdom"),
        AirportInfo(iata: "LPL", name: "Liverpool John Lennon", city: "Liverpool", country: "United Kingdom"),
        AirportInfo(iata: "ORY", name: "Orly", city: "Paris", country: "France"),
        AirportInfo(iata: "NCE", name: "Nice Côte d'Azur", city: "Nice", country: "France"),
        AirportInfo(iata: "LYS", name: "Lyon–Saint-Exupéry", city: "Lyon", country: "France"),
        AirportInfo(iata: "MRS", name: "Marseille Provence", city: "Marseille", country: "France"),
        AirportInfo(iata: "TLS", name: "Toulouse-Blagnac", city: "Toulouse", country: "France"),
        AirportInfo(iata: "BOD", name: "Bordeaux–Mérignac", city: "Bordeaux", country: "France"),
        AirportInfo(iata: "NTE", name: "Nantes Atlantique", city: "Nantes", country: "France"),
        AirportInfo(iata: "MUC", name: "Munich", city: "Munich", country: "Germany"),
        AirportInfo(iata: "BER", name: "Berlin Brandenburg", city: "Berlin", country: "Germany"),
        AirportInfo(iata: "DUS", name: "Düsseldorf", city: "Düsseldorf", country: "Germany"),
        AirportInfo(iata: "HAM", name: "Hamburg", city: "Hamburg", country: "Germany"),
        AirportInfo(iata: "CGN", name: "Cologne Bonn", city: "Cologne", country: "Germany"),
        AirportInfo(iata: "STR", name: "Stuttgart", city: "Stuttgart", country: "Germany"),
        AirportInfo(iata: "HAJ", name: "Hannover", city: "Hannover", country: "Germany"),
        AirportInfo(iata: "NUE", name: "Nuremberg", city: "Nuremberg", country: "Germany"),
        AirportInfo(iata: "LEJ", name: "Leipzig/Halle", city: "Leipzig", country: "Germany"),
        AirportInfo(iata: "MAD", name: "Adolfo Suárez Madrid–Barajas", city: "Madrid", country: "Spain"),
        AirportInfo(iata: "BCN", name: "Barcelona–El Prat", city: "Barcelona", country: "Spain"),
        AirportInfo(iata: "PMI", name: "Palma de Mallorca", city: "Palma", country: "Spain"),
        AirportInfo(iata: "AGP", name: "Málaga–Costa del Sol", city: "Málaga", country: "Spain"),
        AirportInfo(iata: "ALC", name: "Alicante–Elche", city: "Alicante", country: "Spain"),
        AirportInfo(iata: "VLC", name: "Valencia", city: "Valencia", country: "Spain"),
        AirportInfo(iata: "SVQ", name: "Seville", city: "Seville", country: "Spain"),
        AirportInfo(iata: "TFS", name: "Tenerife South", city: "Tenerife", country: "Spain"),
        AirportInfo(iata: "LPA", name: "Gran Canaria", city: "Las Palmas", country: "Spain"),
        AirportInfo(iata: "IBZ", name: "Ibiza", city: "Ibiza", country: "Spain"),
        AirportInfo(iata: "BIO", name: "Bilbao", city: "Bilbao", country: "Spain"),
        AirportInfo(iata: "FCO", name: "Leonardo da Vinci–Fiumicino", city: "Rome", country: "Italy"),
        AirportInfo(iata: "MXP", name: "Milan Malpensa", city: "Milan", country: "Italy"),
        AirportInfo(iata: "LIN", name: "Milan Linate", city: "Milan", country: "Italy"),
        AirportInfo(iata: "VCE", name: "Venice Marco Polo", city: "Venice", country: "Italy"),
        AirportInfo(iata: "NAP", name: "Naples", city: "Naples", country: "Italy"),
        AirportInfo(iata: "BGY", name: "Milan Bergamo", city: "Bergamo", country: "Italy"),
        AirportInfo(iata: "BLQ", name: "Bologna Guglielmo Marconi", city: "Bologna", country: "Italy"),
        AirportInfo(iata: "CTA", name: "Catania-Fontanarossa", city: "Catania", country: "Italy"),
        AirportInfo(iata: "PMO", name: "Falcone–Borsellino", city: "Palermo", country: "Italy"),
        AirportInfo(iata: "FLR", name: "Florence Amerigo Vespucci", city: "Florence", country: "Italy"),
        AirportInfo(iata: "PSA", name: "Pisa Galileo Galilei", city: "Pisa", country: "Italy"),
        AirportInfo(iata: "TRN", name: "Turin Caselle", city: "Turin", country: "Italy"),
        AirportInfo(iata: "LIS", name: "Lisbon Humberto Delgado", city: "Lisbon", country: "Portugal"),
        AirportInfo(iata: "OPO", name: "Francisco Sá Carneiro", city: "Porto", country: "Portugal"),
        AirportInfo(iata: "FAO", name: "Faro", city: "Faro", country: "Portugal"),
        AirportInfo(iata: "FNC", name: "Madeira", city: "Funchal", country: "Portugal"),
        AirportInfo(iata: "PDL", name: "João Paulo II", city: "Ponta Delgada", country: "Portugal"),
        AirportInfo(iata: "ZRH", name: "Zürich", city: "Zürich", country: "Switzerland"),
        AirportInfo(iata: "GVA", name: "Geneva", city: "Geneva", country: "Switzerland"),
        AirportInfo(iata: "BSL", name: "EuroAirport Basel-Mulhouse", city: "Basel", country: "Switzerland"),
        AirportInfo(iata: "VIE", name: "Vienna Intl", city: "Vienna", country: "Austria"),
        AirportInfo(iata: "SZG", name: "Salzburg", city: "Salzburg", country: "Austria"),
        AirportInfo(iata: "INN", name: "Innsbruck", city: "Innsbruck", country: "Austria"),
        AirportInfo(iata: "BRU", name: "Brussels", city: "Brussels", country: "Belgium"),
        AirportInfo(iata: "CRL", name: "Brussels South Charleroi", city: "Charleroi", country: "Belgium"),
        AirportInfo(iata: "DUB", name: "Dublin", city: "Dublin", country: "Ireland"),
        AirportInfo(iata: "SNN", name: "Shannon", city: "Shannon", country: "Ireland"),
        AirportInfo(iata: "ORK", name: "Cork", city: "Cork", country: "Ireland"),
        AirportInfo(iata: "CPH", name: "Copenhagen Kastrup", city: "Copenhagen", country: "Denmark"),
        AirportInfo(iata: "OSL", name: "Oslo Gardermoen", city: "Oslo", country: "Norway"),
        AirportInfo(iata: "BGO", name: "Bergen Flesland", city: "Bergen", country: "Norway"),
        AirportInfo(iata: "TRD", name: "Trondheim Værnes", city: "Trondheim", country: "Norway"),
        AirportInfo(iata: "SVG", name: "Stavanger Sola", city: "Stavanger", country: "Norway"),
        AirportInfo(iata: "TOS", name: "Tromsø Langnes", city: "Tromsø", country: "Norway"),
        AirportInfo(iata: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden"),
        AirportInfo(iata: "GOT", name: "Göteborg Landvetter", city: "Gothenburg", country: "Sweden"),
        AirportInfo(iata: "MMX", name: "Malmö Sturup", city: "Malmö", country: "Sweden"),
        AirportInfo(iata: "HEL", name: "Helsinki-Vantaa", city: "Helsinki", country: "Finland"),
        AirportInfo(iata: "KEF", name: "Keflavík Intl", city: "Reykjavík", country: "Iceland"),
        AirportInfo(iata: "ATH", name: "Athens Intl Eleftherios Venizelos", city: "Athens", country: "Greece"),
        AirportInfo(iata: "SKG", name: "Thessaloniki Macedonia Intl", city: "Thessaloniki", country: "Greece"),
        AirportInfo(iata: "HER", name: "Heraklion Intl", city: "Heraklion", country: "Greece"),
        AirportInfo(iata: "RHO", name: "Rhodes Diagoras", city: "Rhodes", country: "Greece"),
        AirportInfo(iata: "CFU", name: "Corfu Ioannis Kapodistrias", city: "Corfu", country: "Greece"),
        AirportInfo(iata: "JTR", name: "Santorini", city: "Santorini", country: "Greece"),
        AirportInfo(iata: "JMK", name: "Mykonos", city: "Mykonos", country: "Greece"),
        AirportInfo(iata: "WAW", name: "Warsaw Chopin", city: "Warsaw", country: "Poland"),
        AirportInfo(iata: "KRK", name: "John Paul II Intl Kraków–Balice", city: "Kraków", country: "Poland"),
        AirportInfo(iata: "GDN", name: "Gdańsk Lech Wałęsa", city: "Gdańsk", country: "Poland"),
        AirportInfo(iata: "WRO", name: "Copernicus Wrocław", city: "Wrocław", country: "Poland"),
        AirportInfo(iata: "PRG", name: "Václav Havel Prague", city: "Prague", country: "Czech Republic"),
        AirportInfo(iata: "BUD", name: "Budapest Ferenc Liszt Intl", city: "Budapest", country: "Hungary"),
        AirportInfo(iata: "OTP", name: "Henri Coandă Intl", city: "Bucharest", country: "Romania"),
        AirportInfo(iata: "CLJ", name: "Avram Iancu Cluj Intl", city: "Cluj-Napoca", country: "Romania"),
        AirportInfo(iata: "SOF", name: "Sofia", city: "Sofia", country: "Bulgaria"),
        AirportInfo(iata: "BOJ", name: "Burgas", city: "Burgas", country: "Bulgaria"),
        AirportInfo(iata: "VAR", name: "Varna", city: "Varna", country: "Bulgaria"),
        AirportInfo(iata: "BEG", name: "Belgrade Nikola Tesla", city: "Belgrade", country: "Serbia"),
        AirportInfo(iata: "ZAG", name: "Zagreb Franjo Tuđman", city: "Zagreb", country: "Croatia"),
        AirportInfo(iata: "SPU", name: "Split", city: "Split", country: "Croatia"),
        AirportInfo(iata: "DBV", name: "Dubrovnik", city: "Dubrovnik", country: "Croatia"),
        AirportInfo(iata: "LJU", name: "Ljubljana Jože Pučnik", city: "Ljubljana", country: "Slovenia"),
        AirportInfo(iata: "TLL", name: "Tallinn Lennart Meri", city: "Tallinn", country: "Estonia"),
        AirportInfo(iata: "RIX", name: "Riga Intl", city: "Riga", country: "Latvia"),
        AirportInfo(iata: "VNO", name: "Vilnius Intl", city: "Vilnius", country: "Lithuania"),
        AirportInfo(iata: "KIV", name: "Chișinău Intl", city: "Chișinău", country: "Moldova"),
        AirportInfo(iata: "SKP", name: "Skopje Intl", city: "Skopje", country: "North Macedonia"),
        AirportInfo(iata: "TIA", name: "Tirana Intl Nënë Tereza", city: "Tirana", country: "Albania"),
        AirportInfo(iata: "MLA", name: "Malta Intl", city: "Valletta", country: "Malta"),
        AirportInfo(iata: "LCA", name: "Larnaca Intl", city: "Larnaca", country: "Cyprus"),
        AirportInfo(iata: "PFO", name: "Paphos Intl", city: "Paphos", country: "Cyprus"),
        // Middle East
        AirportInfo(iata: "AUH", name: "Abu Dhabi Intl", city: "Abu Dhabi", country: "United Arab Emirates"),
        AirportInfo(iata: "SHJ", name: "Sharjah Intl", city: "Sharjah", country: "United Arab Emirates"),
        AirportInfo(iata: "DWC", name: "Al Maktoum Intl", city: "Dubai", country: "United Arab Emirates"),
        AirportInfo(iata: "DOH", name: "Hamad Intl", city: "Doha", country: "Qatar"),
        AirportInfo(iata: "BAH", name: "Bahrain Intl", city: "Manama", country: "Bahrain"),
        AirportInfo(iata: "KWI", name: "Kuwait Intl", city: "Kuwait City", country: "Kuwait"),
        AirportInfo(iata: "MCT", name: "Muscat Intl", city: "Muscat", country: "Oman"),
        AirportInfo(iata: "RUH", name: "King Khalid Intl", city: "Riyadh", country: "Saudi Arabia"),
        AirportInfo(iata: "JED", name: "King Abdulaziz Intl", city: "Jeddah", country: "Saudi Arabia"),
        AirportInfo(iata: "DMM", name: "King Fahd Intl", city: "Dammam", country: "Saudi Arabia"),
        AirportInfo(iata: "MED", name: "Prince Mohammad bin Abdulaziz Intl", city: "Medina", country: "Saudi Arabia"),
        AirportInfo(iata: "TLV", name: "Ben Gurion Intl", city: "Tel Aviv", country: "Israel"),
        AirportInfo(iata: "AMM", name: "Queen Alia Intl", city: "Amman", country: "Jordan"),
        AirportInfo(iata: "BEY", name: "Rafic Hariri Intl", city: "Beirut", country: "Lebanon"),
        AirportInfo(iata: "IKA", name: "Imam Khomeini Intl", city: "Tehran", country: "Iran"),
        AirportInfo(iata: "BGW", name: "Baghdad Intl", city: "Baghdad", country: "Iraq"),
        AirportInfo(iata: "EBL", name: "Erbil Intl", city: "Erbil", country: "Iraq"),
        AirportInfo(iata: "SAW", name: "Sabiha Gökçen Intl", city: "Istanbul", country: "Turkey"),
        AirportInfo(iata: "AYT", name: "Antalya", city: "Antalya", country: "Turkey"),
        AirportInfo(iata: "ESB", name: "Esenboğa Intl", city: "Ankara", country: "Turkey"),
        AirportInfo(iata: "ADB", name: "Adnan Menderes", city: "Izmir", country: "Turkey"),
        AirportInfo(iata: "DLM", name: "Dalaman", city: "Dalaman", country: "Turkey"),
        AirportInfo(iata: "BJV", name: "Milas-Bodrum", city: "Bodrum", country: "Turkey"),
        AirportInfo(iata: "TZX", name: "Trabzon", city: "Trabzon", country: "Turkey"),
        // Asia Pacific
        AirportInfo(iata: "HKG", name: "Hong Kong Intl", city: "Hong Kong", country: "Hong Kong"),
        AirportInfo(iata: "PVG", name: "Shanghai Pudong Intl", city: "Shanghai", country: "China"),
        AirportInfo(iata: "SHA", name: "Shanghai Hongqiao Intl", city: "Shanghai", country: "China"),
        AirportInfo(iata: "CKG", name: "Chongqing Jiangbei Intl", city: "Chongqing", country: "China"),
        AirportInfo(iata: "CTU", name: "Chengdu Shuangliu Intl", city: "Chengdu", country: "China"),
        AirportInfo(iata: "TFU", name: "Chengdu Tianfu Intl", city: "Chengdu", country: "China"),
        AirportInfo(iata: "SZX", name: "Shenzhen Bao'an Intl", city: "Shenzhen", country: "China"),
        AirportInfo(iata: "KMG", name: "Kunming Changshui Intl", city: "Kunming", country: "China"),
        AirportInfo(iata: "XIY", name: "Xi'an Xianyang Intl", city: "Xi'an", country: "China"),
        AirportInfo(iata: "HGH", name: "Hangzhou Xiaoshan Intl", city: "Hangzhou", country: "China"),
        AirportInfo(iata: "NKG", name: "Nanjing Lukou Intl", city: "Nanjing", country: "China"),
        AirportInfo(iata: "WUH", name: "Wuhan Tianhe Intl", city: "Wuhan", country: "China"),
        AirportInfo(iata: "CSX", name: "Changsha Huanghua Intl", city: "Changsha", country: "China"),
        AirportInfo(iata: "TAO", name: "Qingdao Jiaodong Intl", city: "Qingdao", country: "China"),
        AirportInfo(iata: "XMN", name: "Xiamen Gaoqi Intl", city: "Xiamen", country: "China"),
        AirportInfo(iata: "HAK", name: "Haikou Meilan Intl", city: "Haikou", country: "China"),
        AirportInfo(iata: "SYX", name: "Sanya Phoenix Intl", city: "Sanya", country: "China"),
        AirportInfo(iata: "TPE", name: "Taiwan Taoyuan Intl", city: "Taipei", country: "Taiwan"),
        AirportInfo(iata: "TSA", name: "Taipei Songshan", city: "Taipei", country: "Taiwan"),
        AirportInfo(iata: "KHH", name: "Kaohsiung Intl", city: "Kaohsiung", country: "Taiwan"),
        AirportInfo(iata: "KIX", name: "Kansai Intl", city: "Osaka", country: "Japan"),
        AirportInfo(iata: "ITM", name: "Osaka Itami", city: "Osaka", country: "Japan"),
        AirportInfo(iata: "NGO", name: "Chubu Centrair Intl", city: "Nagoya", country: "Japan"),
        AirportInfo(iata: "FUK", name: "Fukuoka", city: "Fukuoka", country: "Japan"),
        AirportInfo(iata: "CTS", name: "New Chitose", city: "Sapporo", country: "Japan"),
        AirportInfo(iata: "OKA", name: "Naha", city: "Okinawa", country: "Japan"),
        AirportInfo(iata: "GMP", name: "Gimpo Intl", city: "Seoul", country: "South Korea"),
        AirportInfo(iata: "PUS", name: "Gimhae Intl", city: "Busan", country: "South Korea"),
        AirportInfo(iata: "CJU", name: "Jeju Intl", city: "Jeju", country: "South Korea"),
        AirportInfo(iata: "MNL", name: "Ninoy Aquino Intl", city: "Manila", country: "Philippines"),
        AirportInfo(iata: "CEB", name: "Mactan-Cebu Intl", city: "Cebu", country: "Philippines"),
        AirportInfo(iata: "CRK", name: "Clark Intl", city: "Angeles City", country: "Philippines"),
        AirportInfo(iata: "KUL", name: "Kuala Lumpur Intl", city: "Kuala Lumpur", country: "Malaysia"),
        AirportInfo(iata: "PEN", name: "Penang Intl", city: "Penang", country: "Malaysia"),
        AirportInfo(iata: "BKI", name: "Kota Kinabalu Intl", city: "Kota Kinabalu", country: "Malaysia"),
        AirportInfo(iata: "KCH", name: "Kuching Intl", city: "Kuching", country: "Malaysia"),
        AirportInfo(iata: "LGK", name: "Langkawi Intl", city: "Langkawi", country: "Malaysia"),
        AirportInfo(iata: "CGK", name: "Soekarno-Hatta Intl", city: "Jakarta", country: "Indonesia"),
        AirportInfo(iata: "DPS", name: "Ngurah Rai Intl", city: "Bali", country: "Indonesia"),
        AirportInfo(iata: "SUB", name: "Juanda Intl", city: "Surabaya", country: "Indonesia"),
        AirportInfo(iata: "UPG", name: "Sultan Hasanuddin Intl", city: "Makassar", country: "Indonesia"),
        AirportInfo(iata: "YIA", name: "Yogyakarta Intl", city: "Yogyakarta", country: "Indonesia"),
        AirportInfo(iata: "DMK", name: "Don Mueang Intl", city: "Bangkok", country: "Thailand"),
        AirportInfo(iata: "CNX", name: "Chiang Mai Intl", city: "Chiang Mai", country: "Thailand"),
        AirportInfo(iata: "HKT", name: "Phuket Intl", city: "Phuket", country: "Thailand"),
        AirportInfo(iata: "USM", name: "Samui", city: "Koh Samui", country: "Thailand"),
        AirportInfo(iata: "SGN", name: "Tan Son Nhat Intl", city: "Ho Chi Minh City", country: "Vietnam"),
        AirportInfo(iata: "HAN", name: "Noi Bai Intl", city: "Hanoi", country: "Vietnam"),
        AirportInfo(iata: "DAD", name: "Da Nang Intl", city: "Da Nang", country: "Vietnam"),
        AirportInfo(iata: "CXR", name: "Cam Ranh Intl", city: "Nha Trang", country: "Vietnam"),
        AirportInfo(iata: "PQC", name: "Phu Quoc Intl", city: "Phu Quoc", country: "Vietnam"),
        AirportInfo(iata: "PNH", name: "Phnom Penh Intl", city: "Phnom Penh", country: "Cambodia"),
        AirportInfo(iata: "REP", name: "Siem Reap-Angkor Intl", city: "Siem Reap", country: "Cambodia"),
        AirportInfo(iata: "VTE", name: "Wattay Intl", city: "Vientiane", country: "Laos"),
        AirportInfo(iata: "RGN", name: "Yangon Intl", city: "Yangon", country: "Myanmar"),
        AirportInfo(iata: "MFM", name: "Macau Intl", city: "Macau", country: "Macau"),
        AirportInfo(iata: "BOM", name: "Chhatrapati Shivaji Maharaj Intl", city: "Mumbai", country: "India"),
        AirportInfo(iata: "BLR", name: "Kempegowda Intl", city: "Bengaluru", country: "India"),
        AirportInfo(iata: "MAA", name: "Chennai Intl", city: "Chennai", country: "India"),
        AirportInfo(iata: "HYD", name: "Rajiv Gandhi Intl", city: "Hyderabad", country: "India"),
        AirportInfo(iata: "CCU", name: "Netaji Subhas Chandra Bose Intl", city: "Kolkata", country: "India"),
        AirportInfo(iata: "COK", name: "Cochin Intl", city: "Kochi", country: "India"),
        AirportInfo(iata: "GOI", name: "Goa Intl", city: "Goa", country: "India"),
        AirportInfo(iata: "AMD", name: "Sardar Vallabhbhai Patel Intl", city: "Ahmedabad", country: "India"),
        AirportInfo(iata: "JAI", name: "Jaipur Intl", city: "Jaipur", country: "India"),
        AirportInfo(iata: "PNQ", name: "Pune", city: "Pune", country: "India"),
        AirportInfo(iata: "GAU", name: "Lokpriya Gopinath Bordoloi Intl", city: "Guwahati", country: "India"),
        AirportInfo(iata: "TRV", name: "Trivandrum Intl", city: "Thiruvananthapuram", country: "India"),
        AirportInfo(iata: "ISB", name: "Islamabad Intl", city: "Islamabad", country: "Pakistan"),
        AirportInfo(iata: "KHI", name: "Jinnah Intl", city: "Karachi", country: "Pakistan"),
        AirportInfo(iata: "LHE", name: "Allama Iqbal Intl", city: "Lahore", country: "Pakistan"),
        AirportInfo(iata: "DAC", name: "Hazrat Shahjalal Intl", city: "Dhaka", country: "Bangladesh"),
        AirportInfo(iata: "CMB", name: "Bandaranaike Intl", city: "Colombo", country: "Sri Lanka"),
        AirportInfo(iata: "MLE", name: "Velana Intl", city: "Malé", country: "Maldives"),
        AirportInfo(iata: "KTM", name: "Tribhuvan Intl", city: "Kathmandu", country: "Nepal"),
        // Oceania
        AirportInfo(iata: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia"),
        AirportInfo(iata: "MEL", name: "Melbourne Tullamarine", city: "Melbourne", country: "Australia"),
        AirportInfo(iata: "BNE", name: "Brisbane", city: "Brisbane", country: "Australia"),
        AirportInfo(iata: "PER", name: "Perth", city: "Perth", country: "Australia"),
        AirportInfo(iata: "ADL", name: "Adelaide", city: "Adelaide", country: "Australia"),
        AirportInfo(iata: "OOL", name: "Gold Coast", city: "Gold Coast", country: "Australia"),
        AirportInfo(iata: "CBR", name: "Canberra", city: "Canberra", country: "Australia"),
        AirportInfo(iata: "CNS", name: "Cairns", city: "Cairns", country: "Australia"),
        AirportInfo(iata: "HBA", name: "Hobart", city: "Hobart", country: "Australia"),
        AirportInfo(iata: "DRW", name: "Darwin Intl", city: "Darwin", country: "Australia"),
        AirportInfo(iata: "TSV", name: "Townsville", city: "Townsville", country: "Australia"),
        AirportInfo(iata: "AKL", name: "Auckland", city: "Auckland", country: "New Zealand"),
        AirportInfo(iata: "CHC", name: "Christchurch Intl", city: "Christchurch", country: "New Zealand"),
        AirportInfo(iata: "WLG", name: "Wellington Intl", city: "Wellington", country: "New Zealand"),
        AirportInfo(iata: "ZQN", name: "Queenstown", city: "Queenstown", country: "New Zealand"),
        AirportInfo(iata: "NAN", name: "Nadi Intl", city: "Nadi", country: "Fiji"),
        AirportInfo(iata: "PPT", name: "Faa'a Intl", city: "Papeete", country: "French Polynesia"),
        AirportInfo(iata: "NOU", name: "La Tontouta Intl", city: "Nouméa", country: "New Caledonia"),
        // Africa
        AirportInfo(iata: "JNB", name: "O.R. Tambo Intl", city: "Johannesburg", country: "South Africa"),
        AirportInfo(iata: "CPT", name: "Cape Town Intl", city: "Cape Town", country: "South Africa"),
        AirportInfo(iata: "DUR", name: "King Shaka Intl", city: "Durban", country: "South Africa"),
        AirportInfo(iata: "CAI", name: "Cairo Intl", city: "Cairo", country: "Egypt"),
        AirportInfo(iata: "HRG", name: "Hurghada Intl", city: "Hurghada", country: "Egypt"),
        AirportInfo(iata: "SSH", name: "Sharm el-Sheikh Intl", city: "Sharm el-Sheikh", country: "Egypt"),
        AirportInfo(iata: "LXR", name: "Luxor Intl", city: "Luxor", country: "Egypt"),
        AirportInfo(iata: "CMN", name: "Mohammed V Intl", city: "Casablanca", country: "Morocco"),
        AirportInfo(iata: "RAK", name: "Marrakech Menara", city: "Marrakech", country: "Morocco"),
        AirportInfo(iata: "TNG", name: "Tangier Ibn Battouta", city: "Tangier", country: "Morocco"),
        AirportInfo(iata: "FEZ", name: "Fès–Saïss", city: "Fez", country: "Morocco"),
        AirportInfo(iata: "AGA", name: "Agadir–Al Massira", city: "Agadir", country: "Morocco"),
        AirportInfo(iata: "TUN", name: "Tunis-Carthage Intl", city: "Tunis", country: "Tunisia"),
        AirportInfo(iata: "ALG", name: "Houari Boumediene", city: "Algiers", country: "Algeria"),
        AirportInfo(iata: "NBO", name: "Jomo Kenyatta Intl", city: "Nairobi", country: "Kenya"),
        AirportInfo(iata: "MBA", name: "Moi Intl", city: "Mombasa", country: "Kenya"),
        AirportInfo(iata: "ADD", name: "Addis Ababa Bole Intl", city: "Addis Ababa", country: "Ethiopia"),
        AirportInfo(iata: "LOS", name: "Murtala Muhammed Intl", city: "Lagos", country: "Nigeria"),
        AirportInfo(iata: "ABV", name: "Nnamdi Azikiwe Intl", city: "Abuja", country: "Nigeria"),
        AirportInfo(iata: "ACC", name: "Kotoka Intl", city: "Accra", country: "Ghana"),
        AirportInfo(iata: "DSS", name: "Blaise Diagne Intl", city: "Dakar", country: "Senegal"),
        AirportInfo(iata: "DAR", name: "Julius Nyerere Intl", city: "Dar es Salaam", country: "Tanzania"),
        AirportInfo(iata: "ZNZ", name: "Abeid Amani Karume Intl", city: "Zanzibar", country: "Tanzania"),
        AirportInfo(iata: "JRO", name: "Kilimanjaro Intl", city: "Kilimanjaro", country: "Tanzania"),
        AirportInfo(iata: "EBB", name: "Entebbe Intl", city: "Entebbe", country: "Uganda"),
        AirportInfo(iata: "KGL", name: "Kigali Intl", city: "Kigali", country: "Rwanda"),
        AirportInfo(iata: "MRU", name: "Sir Seewoosagur Ramgoolam Intl", city: "Mauritius", country: "Mauritius"),
        AirportInfo(iata: "TNR", name: "Ivato Intl", city: "Antananarivo", country: "Madagascar"),
        AirportInfo(iata: "WDH", name: "Hosea Kutako Intl", city: "Windhoek", country: "Namibia"),
        AirportInfo(iata: "SEZ", name: "Seychelles Intl", city: "Mahé", country: "Seychelles"),
        AirportInfo(iata: "LUN", name: "Kenneth Kaunda Intl", city: "Lusaka", country: "Zambia"),
        AirportInfo(iata: "HRE", name: "Robert Gabriel Mugabe Intl", city: "Harare", country: "Zimbabwe"),
        AirportInfo(iata: "VFA", name: "Victoria Falls", city: "Victoria Falls", country: "Zimbabwe"),
        AirportInfo(iata: "GBE", name: "Sir Seretse Khama Intl", city: "Gaborone", country: "Botswana"),
        AirportInfo(iata: "MPM", name: "Maputo Intl", city: "Maputo", country: "Mozambique"),
        AirportInfo(iata: "ABJ", name: "Félix-Houphouët-Boigny Intl", city: "Abidjan", country: "Côte d'Ivoire"),
        AirportInfo(iata: "DKR", name: "Léopold Sédar Senghor Intl", city: "Dakar", country: "Senegal"),
        // Central & South America
        AirportInfo(iata: "MEX", name: "Mexico City Intl", city: "Mexico City", country: "Mexico"),
        AirportInfo(iata: "CUN", name: "Cancún Intl", city: "Cancún", country: "Mexico"),
        AirportInfo(iata: "GDL", name: "Miguel Hidalgo y Costilla Intl", city: "Guadalajara", country: "Mexico"),
        AirportInfo(iata: "MTY", name: "General Mariano Escobedo Intl", city: "Monterrey", country: "Mexico"),
        AirportInfo(iata: "TIJ", name: "General Abelardo L. Rodríguez Intl", city: "Tijuana", country: "Mexico"),
        AirportInfo(iata: "SJD", name: "San José del Cabo Intl", city: "Los Cabos", country: "Mexico"),
        AirportInfo(iata: "PVR", name: "Licenciado Gustavo Díaz Ordaz Intl", city: "Puerto Vallarta", country: "Mexico"),
        AirportInfo(iata: "MID", name: "Manuel Crescencio Rejón Intl", city: "Mérida", country: "Mexico"),
        AirportInfo(iata: "BJX", name: "Del Bajío Intl", city: "León", country: "Mexico"),
        AirportInfo(iata: "QRO", name: "Querétaro Intercontinental", city: "Querétaro", country: "Mexico"),
        AirportInfo(iata: "GUA", name: "La Aurora Intl", city: "Guatemala City", country: "Guatemala"),
        AirportInfo(iata: "SAL", name: "Monseñor Óscar Arnulfo Romero Intl", city: "San Salvador", country: "El Salvador"),
        AirportInfo(iata: "SAP", name: "Ramón Villeda Morales Intl", city: "San Pedro Sula", country: "Honduras"),
        AirportInfo(iata: "RTB", name: "Juan Manuel Gálvez Intl", city: "Roatán", country: "Honduras"),
        AirportInfo(iata: "MGA", name: "Augusto C. Sandino Intl", city: "Managua", country: "Nicaragua"),
        AirportInfo(iata: "SJO", name: "Juan Santamaría Intl", city: "San José", country: "Costa Rica"),
        AirportInfo(iata: "LIR", name: "Daniel Oduber Quirós Intl", city: "Liberia", country: "Costa Rica"),
        AirportInfo(iata: "PTY", name: "Tocumen Intl", city: "Panama City", country: "Panama"),
        AirportInfo(iata: "HAV", name: "José Martí Intl", city: "Havana", country: "Cuba"),
        AirportInfo(iata: "VRA", name: "Juan Gualberto Gómez Intl", city: "Varadero", country: "Cuba"),
        AirportInfo(iata: "NAS", name: "Lynden Pindling Intl", city: "Nassau", country: "Bahamas"),
        AirportInfo(iata: "MBJ", name: "Sangster Intl", city: "Montego Bay", country: "Jamaica"),
        AirportInfo(iata: "KIN", name: "Norman Manley Intl", city: "Kingston", country: "Jamaica"),
        AirportInfo(iata: "POS", name: "Piarco Intl", city: "Port of Spain", country: "Trinidad and Tobago"),
        AirportInfo(iata: "SDQ", name: "Las Américas Intl", city: "Santo Domingo", country: "Dominican Republic"),
        AirportInfo(iata: "PUJ", name: "Punta Cana Intl", city: "Punta Cana", country: "Dominican Republic"),
        AirportInfo(iata: "SJU", name: "Luis Muñoz Marín Intl", city: "San Juan", country: "Puerto Rico"),
        AirportInfo(iata: "AUA", name: "Queen Beatrix Intl", city: "Oranjestad", country: "Aruba"),
        AirportInfo(iata: "CUR", name: "Hato Intl", city: "Willemstad", country: "Curaçao"),
        AirportInfo(iata: "SXM", name: "Princess Juliana Intl", city: "Philipsburg", country: "Sint Maarten"),
        AirportInfo(iata: "BGI", name: "Grantley Adams Intl", city: "Bridgetown", country: "Barbados"),
        AirportInfo(iata: "BOG", name: "El Dorado Intl", city: "Bogotá", country: "Colombia"),
        AirportInfo(iata: "MDE", name: "José María Córdova Intl", city: "Medellín", country: "Colombia"),
        AirportInfo(iata: "CTG", name: "Rafael Núñez Intl", city: "Cartagena", country: "Colombia"),
        AirportInfo(iata: "CLO", name: "Alfonso Bonilla Aragón Intl", city: "Cali", country: "Colombia"),
        AirportInfo(iata: "GRU", name: "São Paulo/Guarulhos Intl", city: "São Paulo", country: "Brazil"),
        AirportInfo(iata: "GIG", name: "Rio de Janeiro/Galeão Intl", city: "Rio de Janeiro", country: "Brazil"),
        AirportInfo(iata: "BSB", name: "Presidente Juscelino Kubitschek Intl", city: "Brasília", country: "Brazil"),
        AirportInfo(iata: "CNF", name: "Tancredo Neves Intl", city: "Belo Horizonte", country: "Brazil"),
        AirportInfo(iata: "SSA", name: "Deputado Luís Eduardo Magalhães Intl", city: "Salvador", country: "Brazil"),
        AirportInfo(iata: "REC", name: "Recife/Guararapes Intl", city: "Recife", country: "Brazil"),
        AirportInfo(iata: "FOR", name: "Pinto Martins Intl", city: "Fortaleza", country: "Brazil"),
        AirportInfo(iata: "CWB", name: "Afonso Pena Intl", city: "Curitiba", country: "Brazil"),
        AirportInfo(iata: "POA", name: "Salgado Filho Intl", city: "Porto Alegre", country: "Brazil"),
        AirportInfo(iata: "FLN", name: "Hercílio Luz Intl", city: "Florianópolis", country: "Brazil"),
        AirportInfo(iata: "VCP", name: "Viracopos Intl", city: "Campinas", country: "Brazil"),
        AirportInfo(iata: "MAO", name: "Eduardo Gomes Intl", city: "Manaus", country: "Brazil"),
        AirportInfo(iata: "BEL", name: "Val de Cans Intl", city: "Belém", country: "Brazil"),
        AirportInfo(iata: "NAT", name: "São Gonçalo do Amarante Intl", city: "Natal", country: "Brazil"),
        AirportInfo(iata: "SDU", name: "Santos Dumont", city: "Rio de Janeiro", country: "Brazil"),
        AirportInfo(iata: "CGH", name: "Congonhas", city: "São Paulo", country: "Brazil"),
        AirportInfo(iata: "EZE", name: "Ministro Pistarini Intl", city: "Buenos Aires", country: "Argentina"),
        AirportInfo(iata: "AEP", name: "Jorge Newbery Airpark", city: "Buenos Aires", country: "Argentina"),
        AirportInfo(iata: "COR", name: "Ingeniero Aeronáutico Ambrosio L.V. Taravella Intl", city: "Córdoba", country: "Argentina"),
        AirportInfo(iata: "MDZ", name: "El Plumerillo Intl", city: "Mendoza", country: "Argentina"),
        AirportInfo(iata: "BRC", name: "Teniente Luis Candelaria", city: "Bariloche", country: "Argentina"),
        AirportInfo(iata: "IGR", name: "Cataratas del Iguazú Intl", city: "Puerto Iguazú", country: "Argentina"),
        AirportInfo(iata: "USH", name: "Malvinas Argentinas Intl", city: "Ushuaia", country: "Argentina"),
        AirportInfo(iata: "SCL", name: "Arturo Merino Benítez Intl", city: "Santiago", country: "Chile"),
        AirportInfo(iata: "IPC", name: "Mataveri Intl", city: "Easter Island", country: "Chile"),
        AirportInfo(iata: "LIM", name: "Jorge Chávez Intl", city: "Lima", country: "Peru"),
        AirportInfo(iata: "CUZ", name: "Alejandro Velasco Astete Intl", city: "Cusco", country: "Peru"),
        AirportInfo(iata: "UIO", name: "Mariscal Sucre Intl", city: "Quito", country: "Ecuador"),
        AirportInfo(iata: "GYE", name: "José Joaquín de Olmedo Intl", city: "Guayaquil", country: "Ecuador"),
        AirportInfo(iata: "GPS", name: "Seymour", city: "Galápagos", country: "Ecuador"),
        AirportInfo(iata: "CCS", name: "Simón Bolívar Intl", city: "Caracas", country: "Venezuela"),
        AirportInfo(iata: "MVD", name: "Carrasco Intl", city: "Montevideo", country: "Uruguay"),
        AirportInfo(iata: "ASU", name: "Silvio Pettirossi Intl", city: "Asunción", country: "Paraguay"),
        AirportInfo(iata: "VVI", name: "Viru Viru Intl", city: "Santa Cruz", country: "Bolivia"),
        AirportInfo(iata: "LPB", name: "El Alto Intl", city: "La Paz", country: "Bolivia"),
        // Central Asia & Russia
        AirportInfo(iata: "SVO", name: "Sheremetyevo Intl", city: "Moscow", country: "Russia"),
        AirportInfo(iata: "DME", name: "Domodedovo Intl", city: "Moscow", country: "Russia"),
        AirportInfo(iata: "LED", name: "Pulkovo", city: "St. Petersburg", country: "Russia"),
        AirportInfo(iata: "ALA", name: "Almaty Intl", city: "Almaty", country: "Kazakhstan"),
        AirportInfo(iata: "NQZ", name: "Nursultan Nazarbayev Intl", city: "Astana", country: "Kazakhstan"),
        AirportInfo(iata: "TAS", name: "Islam Karimov Tashkent Intl", city: "Tashkent", country: "Uzbekistan"),
        AirportInfo(iata: "GYD", name: "Heydar Aliyev Intl", city: "Baku", country: "Azerbaijan"),
        AirportInfo(iata: "TBS", name: "Tbilisi Intl", city: "Tbilisi", country: "Georgia"),
        AirportInfo(iata: "EVN", name: "Zvartnots Intl", city: "Yerevan", country: "Armenia"),
        // Caribbean & Islands
        AirportInfo(iata: "STT", name: "Cyril E. King", city: "St. Thomas", country: "US Virgin Islands"),
        AirportInfo(iata: "STX", name: "Henry E. Rohlsen", city: "St. Croix", country: "US Virgin Islands"),
        AirportInfo(iata: "PTP", name: "Pointe-à-Pitre Le Raizet", city: "Guadeloupe", country: "Guadeloupe"),
        AirportInfo(iata: "FDF", name: "Martinique Aimé Césaire Intl", city: "Fort-de-France", country: "Martinique"),
        AirportInfo(iata: "GND", name: "Maurice Bishop Intl", city: "St. George's", country: "Grenada"),
        AirportInfo(iata: "UVF", name: "Hewanorra Intl", city: "Vieux Fort", country: "Saint Lucia"),
        AirportInfo(iata: "ANU", name: "V.C. Bird Intl", city: "St. John's", country: "Antigua and Barbuda"),
        AirportInfo(iata: "TAB", name: "A.N.R. Robinson Intl", city: "Tobago", country: "Trinidad and Tobago"),
        AirportInfo(iata: "BDA", name: "L.F. Wade Intl", city: "Hamilton", country: "Bermuda"),
        AirportInfo(iata: "GCM", name: "Owen Roberts Intl", city: "George Town", country: "Cayman Islands"),
        AirportInfo(iata: "TCI", name: "Providenciales Intl", city: "Providenciales", country: "Turks and Caicos"),
    ]
}
